[package]
name = "ntt-fuzz"
version = "0.0.1"

[[bin]]
name = "ntt-fuzz"
path = "fuzz_trimmed_amount.rs"

edition = "2021"
[dependencies]
ntt-messages = { path = "../../modules/ntt-messages" }
honggfuzz = "0.5"
arbitrary = { version = "1", optional = true, features = ["derive"] }

[workspace]
